### ISSUE TITLE
Plugin bug for my server

### ISSUE THREAD

**Issue by eR0oT** [IvanCraft623/MobPlugin#9]
Hello, I have installed your plugin on my server, but it's not working. The plugin is enabled, but zombies and other entities have no intelligence and remain immobile. I'm not sure what could be causing this issue.
https://timings.pmmp.io/?id=303308

**Comment by IvanCraft623** [comment]
Hello! as the README says in large the plugin is incomplete, actually in the current state it does not have any implemented entity, the code there are the bases to implement the mobs.

You can try again when the README says that the plugin is ready for use or has some entities implemented.

However I will leave this issue open in case someone else has the same question.

**Comment by IvanCraft623** [comment]
Closed in favor of having feature tracking in a single issue.
